import Layout from '@/components/Layout';
import ThreeScene from '@/components/ThreeScene';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <Layout title="CodeArena - Master Coding">
      <ThreeScene />
      {/* Hero Section */}
      <div className={styles.hero}>
        <div className="container">
          <h1 className={styles.title}>Master Coding.</h1>
          <p className={styles.subtitle}>One Challenge at a Time.</p>
          <p className={styles.description}>
            An AI-powered platform designed to help developers improve their skills
            through unlimited challenges, real-time feedback, and competitive rankings.
          </p>
          <div className={styles.cta}>
            <Link href="/login" className="btn">
              Get Started
            </Link>
            <Link href="/leaderboard" className={styles.secondaryBtn}>
              View Leaderboard
            </Link>
          </div>
        </div>
      </div>

      {/* Stats Section */}
      <div className={styles.statsSection}>
        <div className="container">
          <div className={styles.stats}>
            <div className={styles.stat}>
              <div className={styles.statNumber}>Unlimited</div>
              <div className={styles.statLabel}>AI-Generated Challenges</div>
            </div>
            <div className={styles.stat}>
              <div className={styles.statNumber}>2</div>
              <div className={styles.statLabel}>Programming Languages</div>
            </div>
            <div className={styles.stat}>
              <div className={styles.statNumber}>Real-time</div>
              <div className={styles.statLabel}>Code Execution</div>
            </div>
            <div className={styles.stat}>
              <div className={styles.statNumber}>Free</div>
              <div className={styles.statLabel}>Always</div>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="container">
        <div className={styles.sectionHeader}>
          <h2 className={styles.sectionTitle}>Features</h2>
        </div>
        <div className={styles.features}>
          <div className={styles.featureCard}>
            <h3>AI-Powered Challenges</h3>
            <p>Unlimited coding problems generated by Google Gemini AI, tailored to your skill level.</p>
          </div>
          <div className={styles.featureCard}>
            <h3>Browser IDE</h3>
            <p>Write and run code directly in your browser with Monaco editor. No setup required.</p>
          </div>
          <div className={styles.featureCard}>
            <h3>Global Leaderboard</h3>
            <p>Compete with developers worldwide and track your progress through XP and levels.</p>
          </div>
          <div className={styles.featureCard}>
            <h3>Instant Feedback</h3>
            <p>Get immediate test results and detailed feedback to learn and improve faster.</p>
          </div>
          <div className={styles.featureCard}>
            <h3>Progress Tracking</h3>
            <p>Monitor your improvement with detailed statistics and submission history.</p>
          </div>
          <div className={styles.featureCard}>
            <h3>Secure Execution</h3>
            <p>All code runs in isolated Docker containers for safe and reliable execution.</p>
          </div>
        </div>
      </div>

      {/* How It Works Section */}
      <div className={styles.howItWorksSection}>
        <div className="container">
          <div className={styles.sectionHeader}>
            <h2 className={styles.sectionTitle}>How It Works</h2>
          </div>
          <div className={styles.steps}>
            <div className={styles.step}>
              <div className={styles.stepNumber}>01</div>
              <h3>Create Account</h3>
              <p>Sign up using email or OAuth to get started instantly.</p>
            </div>
            <div className={styles.step}>
              <div className={styles.stepNumber}>02</div>
              <h3>Choose Challenge</h3>
              <p>Select difficulty and language to generate a challenge.</p>
            </div>
            <div className={styles.step}>
              <div className={styles.stepNumber}>03</div>
              <h3>Code & Submit</h3>
              <p>Write your solution and submit to earn XP.</p>
            </div>
          </div>
        </div>
      </div>

      {/* Languages Section */}
      <div className="container">
        <div className={styles.sectionHeader}>
          <h2 className={styles.sectionTitle}>Supported Languages</h2>
        </div>
        <div className={styles.languages}>
          <div className={styles.languageCard}>
            <div className={styles.languageName}>JavaScript</div>
            <p>Modern ES6+ syntax with Node.js runtime</p>
          </div>
          <div className={styles.languageCard}>
            <div className={styles.languageName}>Java</div>
            <p>Industry-standard Java with full OOP support</p>
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className={styles.ctaSection}>
        <div className="container">
          <h2 className={styles.ctaTitle}>Ready to start?</h2>
          <p className={styles.ctaText}>Join developers worldwide and begin solving challenges today.</p>
          <div className={styles.ctaButtons}>
            <Link href="/login" className="btn">
              Get Started
            </Link>
          </div>
        </div>
      </div>
    </Layout>
  );
}
