import Layout from '@/components/Layout';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <Layout title="CodeArena - Master Coding">
      <div className={styles.hero}>
        <div className="container">
          <h1 className={styles.title}>Master Coding.</h1>
          <p className={styles.subtitle}>One Challenge at a Time.</p>
          <div className={styles.cta}>
            <Link href="/login" className="btn">
              Start Coding Now
            </Link>
          </div>
        </div>
      </div>

      <div className="container">
        <div className={styles.features}>
          <div className={styles.feature}>
            <h3>AI Challenges</h3>
            <p>Infinite coding problems generated by AI, tailored to your skill level.</p>
          </div>
          <div className={styles.feature}>
            <h3>Web Arena</h3>
            <p>Monaco editor for browser-based coding with instant feedback.</p>
          </div>
          <div className={styles.feature}>
            <h3>Global Rankings</h3>
            <p>Compete with developers worldwide and track your progress.</p>
          </div>
        </div>
      </div>
    </Layout>
  );
}
