import Layout from '@/components/Layout';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <Layout>
      <div className={styles.hero}>
        <div className="container">
          <h1 className={styles.title}>
            Master Coding.<br />
            <span className={styles.gradientText}>One Challenge at a Time.</span>
          </h1>
          <p className={styles.subtitle}>
            CodeArena is the ultimate CLI-based coding platform powered by AI.
            Compete, learn, and climb the global leaderboard.
          </p>
          <div className={styles.cta}>
            <Link href="/login" className="btn">
              Start Coding Now
            </Link>
            <Link href="/leaderboard" className={styles.linkBtn}>
              View Leaderboard &gt;
            </Link>
          </div>
        </div>
      </div>

      <div className="container">
        <div className={styles.features}>
          <div className="card">
            <h3>AI Challenges</h3>
            <p>Infinite coding problems generated by Google Gemini, tailored to your skill level.</p>
          </div>
          <div className="card">
            <h3>Web Arena</h3>
            <p>Write, run, and debug code directly in your browser with our powerful Monaco-based IDE.</p>
          </div>
          <div className="card">
            <h3>Global Rankings</h3>
            <p>Compete with developers worldwide and climb the leaderboard to prove your mastery.</p>
          </div>
        </div>
      </div>
    </Layout>
  );
}
